Lesson 1_8
verafes/react-todo pull request #8
Opened 2024-08-20 05:34 UTC by verafes

Connect to Airtable API
Fetch Data from Airtable

2024-08-21 22:07 UTC, AnnaPestova1 requested changes
Hi Vera! Great work. I mentioned small issue related your comment in the question section: `POST method didn't work for me, until I changed title: title -> title: todo.title`

Here is your todo: 
<img width="739" alt="image" src="https://github.com/user-attachments/assets/013dd0b2-0b9f-4a56-b8c4-4179358710d1">

Here is the explanation from our assignment (read it carefully and you will figure out what is the issue)
<img width="598" alt="image" src="https://github.com/user-attachments/assets/97f8dd0a-0fe3-4933-9378-95ec582d1148">

2024-08-23 03:35 UTC, verafes commented
I updated POST method to use Airtable API to create new todo.

2024-08-23 14:29 UTC, AnnaPestova1 commented on src/AddTodoForm.jsx
> +        const newTodo = todoTitle
now this line is unnecessary, you can put todoTitle  in onAddTodo function: onAddTodo(todoTitle);

2024-08-23 14:30 UTC, AnnaPestova1 approved these changes
Hi Vera! Great changes.

2024-08-25 22:00 UTC, verafes commented on src/AddTodoForm.jsx
> +        const newTodo = todoTitle
I removed unnecessary variable. Thank you!

2024-08-25 22:00 UTC, merged